name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest with Allure
        run: pytest --alluredir=allure-results

      - name: Upload Allure results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results
