name: UI + API Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Install Google Chrome
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # Verify Chrome installation
      - name: Check Chrome version
        run: google-chrome --version

      # Run pytest with Allure
      - name: Run Tests
        run: |
          pytest --alluredir=allure-results -v
        continue-on-error: true

      # Generate Allure Report
      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: gh-pages/allure-history
          keep_reports: 20

      # Upload Allure results as artifact
      - name: Upload Allure Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-results
          path: allure-results

      # Upload Allure report as artifact
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-report
          path: allure-report

      # Deploy to GitHub Pages
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report